import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TranslationsProvider from "@/libs/providers/translations-provider";
import { ReactNode } from "react";
import initTranslations, { i18nNamespaces } from "@/libs/i18n/i18n";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
  children: ReactNode;
}

const Layout = async ({ children }: LayoutProps) => {
  const cookiesStore = await cookies();
  const locals = cookiesStore.get("i18next")?.value || "th";
  const { resources } = await initTranslations(locals, i18nNamespaces);

  return (
    <html lang={locals} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TranslationsProvider
          namespaces={i18nNamespaces}
          locale={locals}
          resources={resources}
        >
          {children}
        </TranslationsProvider>
      </body>
    </html>
  );
}

export default Layout;
